CREATE OR REPLACE TRIGGER controlar_stock
BEFORE UPDATE OF stock ON Productos
FOR EACH ROW
BEGIN
    IF :NEW.stock < 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'El stock no puede ser negativo.');
    END IF;
END;

CREATE OR REPLACE TRIGGER validar_data_comanda
BEFORE INSERT ON Comandas
FOR EACH ROW
BEGIN
    IF :NEW.fecha > SYSDATE THEN
        RAISE_APPLICATION_ERROR(-20002, 'La fecha de la comanda no puede ser mas tarde a la fecha actual.');
    END IF;
END;

CREATE TABLE LogsDescomptes (
    id_log NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comanda_id NUMBER,
    descompte_antic NUMBER (5, 2),
    descompte_nou NUMBER (5, 2),
    usuario VARCHAR2(50),
    data_modificacio DATE
);

CREATE OR REPLACE TRIGGER log_descompte_comanda
AFTER UPDATE OF descompte ON Comandas
FOR EACH ROW
BEGIN
IF :OLD.descompte != :NEW.descompte THEN
    INSERT INTO LogsDescomptes (comanda_id, descompte_antic, descompte_nou, usuario, data_modificacio)
    VALUES (:OLD.id_comanda, :OLD.descompte, :NEW.descompte, USER, SYSDATE);
END IF;
END;
