
CREATE TABLE VideosProducte (
    producte_id NUMBER NOT NULL,
    descripcio VARCHAR2(255),
    video BLOB NOT NULL,
    format VARCHAR2(50) NOT NULL,
    durada_segons NUMBER NOT NULL,

    CONSTRAINT pk_videos_producte PRIMARY KEY (producte_id),
    CONSTRAINT fk_videos_producte_producte FOREIGN KEY (producte_id) REFERENCES Productos(id_producte),
    CONSTRAINT chk_format CHECK (format IN ('mp4', 'avi', 'mkv')),
    CONSTRAINT chk_durada CHECK (durada_segons > 0)
)

CREATE TABLE DocumentsContracte (
    client_id NUMBER NOT NULL,
    contracte BLOB NOT NULL,
    tipus_document VARCHAR2(50) NOT NULL,
    mida_bytes NUMBER NOT NULL,

    CONSTRAINT pk_documents_contracte PRIMARY KEY (client_id),
    CONSTRAINT fk_documents_contracte_client FOREIGN KEY (client_id) REFERENCES Clients(id_client),
    CONSTRAINT chk_tipus_document CHECK (tipus_document IN ('pdf')),
    CONSTRAINT chk_mida CHECK (mida_bytes > 0)
)

CREATE OR REPLACE TRIGGER xml_client (p_client_id NUMBER)
RETURN XMLTYPE
IS
    resultat XMLTYPE;
BEGIN
    SELECT XMLELEMENT(
        "client",

        XMLFOREST(
            c.id_client AS "id_client",
            c.nom AS "nom",
            c.email AS "email",
            c.telefon AS "telefon"
        )

        XMLELEMENT(
            "DocumentsContracte",
            XMLAGG(
                XMLELEMENT(
                    "Document",
                    XMLFOREST(
                        d.client_id AS "client_id",
                        d.tipus_document AS "tipus_document",
                        d.mida_bytes AS "mida_bytes"
                    )
                )
            )
        )
    )
    INTO resultat
    FROM Clients c
    LEFT JOIN DocumentsContracte d ON c.id_client = d.client_id
    WHERE c.id_client = p_client_id
    GROUP BY c.id_client, c.nom, c.email, c.telefon;
    RETURN resultat;
END;

CREATE TABLE RegistresXML (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    xml_data XMLTYPE
);

SELECT x.*
FROM RegistresXML r,
     XMLTABLE(
        '/Videos/Video[DuradaSegons > 60]'
        PASSING r.xml_data
        COLUMNS
            producte_id NUMBER PATH 'ProducteId',
            format VARCHAR2(20) PATH 'Format',
            durada NUMBER PATH 'DuradaSegons'
     ) x;

SELECT r.id,
       XMLCAST(
           XMLQUERY('/Client/IdClient'
                    PASSING r.xml_data
                    RETURNING CONTENT)
           AS VARCHAR2(20)
       ) AS client_id
FROM RegistresXML r
WHERE XMLEXISTS(
    '/Client[ count(DocumentsContracte/Document) > 1 ]'
    PASSING r.xml_data
);

SELECT format, COUNT(*) AS total_videos
FROM RegistresXML r,
     XMLTABLE(
        '/Videos/Video'
        PASSING r.xml_data
        COLUMNS
            format VARCHAR2(20) PATH 'Format'
     )
GROUP BY format;